export const CartActionTypes = {
    TOGGLE_CARD_HIDDEN: 'TOGGLE_CARD_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEMS: 'REMOVE_ITEMS',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_NULLUSER_CART: 'CLEAR_NULLUSER_CART',
    POPULATE_CART_FROM_NULLUSER_CART: 'POPULATE_CART_FROM_NULLUSER_CART'
}